// Centralized blog data and helpers

export const posts = [
    // 15-article dental blog schedule; first 5 today, 10 more biweekly

    // 1
    {
        slug: "welcome-to-our-dental-blog",
        title: "Welcome to Our Dental Blog",
        excerpt: "What to expect from our upcoming oral health articles.",
        content: [
            "Welcome to the Hentges Dental blog! Every two weeks, we'll share practical tips, explanations of procedures, and patient-friendly insights to help you make confident decisions about your oral health.",
            "Stay tuned for topics like preventive care, cosmetic treatments, technology we use in-office, and more.",
        ],
        heroImg: "/images/patient-on-computer.jpg",
        publishedAt: "2025-10-13",
    },
    // 2
    {
        slug: "why-regular-dental-checkups-matter",
        title: "Why Regular Dental Checkups Matter",
        excerpt: "Learn how biannual visits keep your teeth and gums healthy and prevent costly dental problems.",
        content: [
            "Regular dental checkups are the cornerstone of preventive oral healthcare. The American Dental Association recommends visiting your dentist every six months, though some patients may need more frequent visits based on their individual risk factors.",
            "",
            "During a routine checkup, our team performs several critical functions:",
            "",
            "• Professional Cleaning: Even with excellent home care, plaque and tartar can accumulate in hard-to-reach areas. Our hygienists use specialized tools to remove these deposits, preventing gum disease and tooth decay.",
            "",
            "• Comprehensive Examination: We check for cavities, gum disease, oral cancer, and other conditions. Early detection means simpler, less expensive treatments.",
            "",
            "• Digital X-rays: When needed, we take digital radiographs to identify problems not visible during a visual exam, such as decay between teeth or bone loss.",
            "",
            "• Oral Cancer Screening: We examine your mouth, tongue, and throat for signs of oral cancer, which affects over 50,000 Americans annually.",
            "",
            "• Preventive Education: We provide personalized advice on brushing, flossing, and dietary choices to optimize your oral health.",
            "",
            "Studies show that patients who maintain regular dental visits have 40% fewer dental problems and spend significantly less on dental care over their lifetime. Prevention truly is the best medicine for your smile."
        ],
        heroImg: "/images/dental-exam.jpg",
        publishedAt: "2025-10-13",
    },
    // 3
    {
        slug: "how-to-brush-and-floss-effectively",
        title: "How to Brush and Floss Effectively",
        excerpt: "Master the fundamentals of proper oral hygiene with these evidence-based brushing and flossing techniques.",
        content: [
            "Proper brushing and flossing are the foundation of good oral health. When done correctly, these daily habits remove plaque—the sticky film of bacteria that causes tooth decay and gum disease.",
            "",
            "The Right Brushing Technique:",
            "",
            "• Choose the Right Tools: Use a soft-bristled toothbrush with fluoride toothpaste. Electric toothbrushes can be more effective for some people, especially those with dexterity issues.",
            "",
            "• Timing: Brush for two minutes, twice daily—morning and before bed. Set a timer or use an electric toothbrush with a built-in timer.",
            "",
            "• Method: Hold your brush at a 45-degree angle to your gums. Use gentle, circular motions rather than harsh scrubbing. Brush all surfaces: outer, inner, and chewing surfaces.",
            "",
            "• Don't Forget: Brush your tongue to remove bacteria and freshen breath.",
            "",
            "Mastering Flossing:",
            "",
            "• Frequency: Floss once daily, preferably before bedtime when saliva production decreases.",
            "",
            "• Technique: Use 18 inches of floss, winding most around your middle fingers. Hold 1-2 inches between your thumbs and index fingers. Gently guide the floss between teeth using a C-shape motion.",
            "",
            "• Be Thorough: Floss both sides of each tooth, including the back of your last molars.",
            "",
            "Common Mistakes to Avoid:",
            "",
            "• Brushing too hard (can damage enamel and gums)",
            "• Using an old toothbrush (replace every 3-4 months)",
            "• Skipping flossing (brushing alone misses 40% of tooth surfaces)",
            "• Rushing through your routine",
            "",
            "Remember: consistency is key. Even perfect technique won't help if you don't maintain these habits daily."
        ],
        heroImg: "/images/tooth.png",
        publishedAt: "2025-10-13",
    },
    // 4
    {
        slug: "cosmetic-dentistry-options-at-hentges-dental",
        title: "Cosmetic Dentistry Options at Hentges Dental",
        excerpt: "Transform your smile with our comprehensive cosmetic dentistry treatments designed to enhance both aesthetics and function.",
        content: [
            "Cosmetic dentistry combines artistry with advanced dental technology to create beautiful, natural-looking smiles. At Hentges Dental, we offer a full range of cosmetic treatments to address various aesthetic concerns.",
            "",
            "Teeth Whitening:",
            "",
            "• In-Office Whitening: Professional-strength whitening treatments that can lighten teeth by 3-8 shades in a single visit",
            "• Take-Home Kits: Custom-fitted trays with professional-grade whitening gel for gradual, controlled whitening at home",
            "• Maintenance: Regular touch-ups to maintain your bright smile",
            "",
            "Porcelain Veneers:",
            "",
            "• Thin Shells: Custom-made porcelain veneers that cover the front surface of teeth to correct chips, gaps, discoloration, or misalignment",
            "• Natural Appearance: High-quality porcelain mimics the light-reflecting properties of natural tooth enamel",
            "• Durability: With proper care, veneers can last 10-15 years or longer",
            "",
            "Dental Bonding:",
            "",
            "• Composite Resin: Tooth-colored material applied to repair chips, fill gaps, or improve tooth shape",
            "• Quick Treatment: Often completed in a single visit",
            "• Cost-Effective: More affordable alternative to veneers for minor corrections",
            "",
            "Crowns and Bridges:",
            "",
            "• Porcelain Crowns: Full-coverage restorations that restore both function and appearance",
            "• All-Ceramic Options: Metal-free crowns for optimal aesthetics and biocompatibility",
            "",
            "Smile Makeovers:",
            "",
            "• Comprehensive Planning: We design complete smile transformations using digital imaging and treatment planning",
            "• Combination Treatments: Often combine multiple procedures for optimal results",
            "",
            "During your consultation, we'll discuss your goals, evaluate your oral health, and recommend the most appropriate treatments for your unique situation. Every smile makeover is customized to enhance your natural beauty while maintaining optimal oral health."
        ],
        heroImg: "/images/veneers.svg",
        publishedAt: "2025-10-13",
    },
    // 5
    {
        slug: "what-to-expect-during-your-first-visit",
        title: "What to Expect During Your First Visit",
        excerpt: "Your comprehensive guide to becoming a new patient at Hentges Dental, from paperwork to treatment planning.",
        content: [
            "We're excited to welcome you to the Hentges Dental family! Your first visit is an important opportunity for us to get to know you and establish a foundation for your long-term oral health.",
            "",
            "Before Your Appointment:",
            "",
            "• Complete New Patient Forms: Download and fill out forms from our website, or arrive 15 minutes early to complete them in our comfortable reception area",
            "• Bring Insurance Information: Have your dental insurance card and any relevant medical history",
            "• List Current Medications: Include all prescription and over-the-counter medications, vitamins, and supplements",
            "• Prepare Questions: Write down any concerns or questions you'd like to discuss",
            "",
            "During Your Visit:",
            "",
            "• Comprehensive Health Review: We'll discuss your medical history, current medications, and any dental concerns",
            "• Oral Examination: Thorough examination of your teeth, gums, and oral tissues",
            "• Digital X-rays: When necessary, we take low-radiation digital radiographs to identify issues not visible during examination",
            "• Periodontal Assessment: Evaluation of gum health and bone support",
            "• Oral Cancer Screening: Examination of your mouth, tongue, and throat",
            "• Professional Cleaning: If appropriate, we'll clean your teeth and remove plaque and tartar",
            "",
            "Treatment Planning:",
            "",
            "• Personalized Care Plan: Based on our findings, we'll create a customized treatment plan addressing your specific needs",
            "• Priority Setting: We'll help you prioritize treatments based on urgency and your preferences",
            "• Financial Discussion: Clear explanation of costs, insurance coverage, and payment options",
            "• Scheduling: We'll schedule any necessary follow-up appointments",
            "",
            "Our Commitment to You:",
            "",
            "• Comfort: We use gentle techniques and offer sedation options for anxious patients",
            "• Education: We explain everything in terms you can understand",
            "• Respect: Your time and concerns are important to us",
            "• Quality Care: We use the latest technology and evidence-based treatments",
            "",
            "Most first visits take 60-90 minutes. We believe in taking the time to thoroughly understand your needs and establish a trusting relationship. Your comfort and confidence in our care are our top priorities."
        ],
        heroImg: "/images/reception-phone.jpg",
        publishedAt: "2025-10-13",
    },
    // 6
    {
        slug: "the-importance-of-fluoride-for-oral-health",
        title: "The Importance of Fluoride for Oral Health",
        excerpt: "Discover how fluoride works to strengthen teeth and prevent cavities, and learn about the best sources for optimal protection.",
        content: [
            "Fluoride is a naturally occurring mineral that has been called \"nature's cavity fighter\" for good reason. It's one of the most effective tools we have for preventing tooth decay and maintaining strong, healthy teeth throughout life.",
            "",
            "How Fluoride Works:",
            "",
            "• Remineralization: Fluoride helps rebuild weakened tooth enamel by attracting calcium and phosphate ions to form fluorapatite, a stronger mineral than the original hydroxyapatite",
            "• Inhibition of Bacteria: Fluoride disrupts the acid production of cavity-causing bacteria, reducing their ability to damage teeth",
            "• Early Decay Reversal: In the early stages of decay, fluoride can actually reverse the process before a cavity forms",
            "",
            "Sources of Fluoride:",
            "",
            "• Fluoridated Water: Community water fluoridation is considered one of the greatest public health achievements of the 20th century, reducing cavities by 25% in children and adults",
            "• Fluoride Toothpaste: Use a pea-sized amount of fluoride toothpaste twice daily for optimal protection",
            "• Professional Treatments: In-office fluoride varnishes and gels provide concentrated protection, especially beneficial for high-risk patients",
            "• Fluoride Mouth Rinses: Prescription-strength rinses can provide additional protection for those at high risk of cavities",
            "",
            "Who Benefits Most:",
            "",
            "• Children: Essential for developing permanent teeth and preventing early childhood cavities",
            "• Adults with Dry Mouth: Reduced saliva increases cavity risk, making fluoride especially important",
            "• Gum Disease Patients: Exposed root surfaces are more susceptible to decay",
            "• Orthodontic Patients: Braces make cleaning more difficult, increasing cavity risk",
            "• Cancer Patients: Radiation and chemotherapy can increase cavity risk",
            "",
            "Safety and Recommendations:",
            "",
            "• Children Under 3: Use a rice-grain-sized amount of fluoride toothpaste",
            "• Children 3-6: Use a pea-sized amount and supervise brushing",
            "• Adults: Use fluoride toothpaste and consider professional treatments if at high risk",
            "",
            "The Centers for Disease Control and Prevention, American Dental Association, and World Health Organization all endorse fluoride use as safe and effective. When used appropriately, fluoride provides significant protection against tooth decay with minimal risk."
        ],
        heroImg: "/images/tooth-sparkle.svg",
        publishedAt: "2025-10-27",
    },
    // 7
    {
        slug: "understanding-gum-disease-signs-and-prevention",
        title: "Understanding Gum Disease: Signs & Prevention",
        excerpt: "Learn to recognize the early warning signs of gum disease and discover effective prevention strategies to protect your oral health.",
        content: [
            "Gum disease (periodontal disease) affects nearly half of American adults over 30, making it one of the most common chronic diseases. Understanding the signs and taking preventive action can save your teeth and protect your overall health.",
            "",
            "Stages of Gum Disease:",
            "",
            "• Gingivitis: The earliest, reversible stage characterized by inflammation, redness, and bleeding gums",
            "• Periodontitis: Advanced stage where the infection spreads to supporting bone and tissues",
            "• Advanced Periodontitis: Severe bone loss and tooth mobility, potentially leading to tooth loss",
            "",
            "Early Warning Signs:",
            "",
            "• Bleeding Gums: Gums that bleed during brushing or flossing (this is NOT normal)",
            "• Redness and Swelling: Inflamed, tender, or puffy gums",
            "• Bad Breath: Persistent halitosis that doesn't improve with oral hygiene",
            "• Receding Gums: Teeth appearing longer as gums pull away",
            "• Loose Teeth: Teeth that feel mobile or shift position",
            "• Pain: Discomfort when chewing or sensitivity to hot/cold",
            "",
            "Risk Factors:",
            "",
            "• Poor Oral Hygiene: Inadequate brushing and flossing",
            "• Smoking: Significantly increases risk and reduces treatment success",
            "• Diabetes: Poorly controlled diabetes increases susceptibility",
            "• Genetics: Family history of gum disease",
            "• Medications: Some drugs can cause gum overgrowth or dry mouth",
            "• Stress: Weakens immune system response",
            "• Poor Nutrition: Vitamin C deficiency and other nutritional issues",
            "",
            "Prevention Strategies:",
            "",
            "• Daily Care: Brush twice daily with fluoride toothpaste and floss once daily",
            "• Regular Cleanings: Professional cleanings every 6 months (or more frequently if recommended)",
            "• Quit Smoking: Eliminate tobacco use to reduce risk significantly",
            "• Manage Health Conditions: Keep diabetes and other conditions well-controlled",
            "• Healthy Diet: Eat a balanced diet rich in vitamins and minerals",
            "• Stress Management: Practice stress-reduction techniques",
            "",
            "Treatment Options:",
            "",
            "• Scaling and Root Planing: Deep cleaning to remove plaque and tartar below the gumline",
            "• Antibiotic Therapy: Local or systemic antibiotics to control infection",
            "• Surgical Treatment: Advanced cases may require gum surgery or bone grafts",
            "• Maintenance: Ongoing professional care to prevent recurrence",
            "",
            "Systemic Health Connections:",
            "",
            "Research shows gum disease is linked to heart disease, stroke, diabetes complications, and pregnancy issues. Treating gum disease can improve overall health outcomes.",
            "",
            "Early detection and treatment are crucial. If you notice any warning signs, schedule an appointment immediately. With proper care, gum disease can often be reversed in its early stages."
        ],
        heroImg: "/images/general-dentistry.svg",
        publishedAt: "2025-11-10",
    },
    // 8
    {
        slug: "tooth-colored-fillings-safe-attractive-restorations",
        title: "Tooth-Colored Fillings: Safe, Attractive Restorations",
        excerpt: "Discover why composite resin fillings offer superior aesthetics, durability, and safety compared to traditional metal fillings.",
        content: [
            "Tooth-colored composite fillings have revolutionized cavity treatment, offering patients a natural-looking, safe, and durable alternative to traditional metal amalgam fillings. At Hentges Dental, we use high-quality composite materials to restore teeth while maintaining their natural beauty.",
            "",
            "What Are Composite Fillings?",
            "",
            "Composite fillings are made from a mixture of plastic resin and fine glass particles. They can be precisely color-matched to your natural teeth, making them virtually invisible when properly placed.",
            "",
            "Advantages of Composite Fillings:",
            "",
            "• Natural Appearance: Seamlessly blend with your tooth color and reflect light like natural enamel",
            "• Conservative Treatment: Require less tooth removal than amalgam fillings, preserving more healthy tooth structure",
            "• Bonding Technology: Chemically bond to tooth structure, providing additional strength and sealing",
            "• Versatility: Can be used for front and back teeth, small and large cavities",
            "• Immediate Use: No waiting period—you can eat normally right after placement",
            "• No Metal Sensitivity: Eliminate concerns about metal allergies or sensitivity",
            "",
            "The Placement Process:",
            "",
            "• Preparation: Remove decay and prepare the tooth for bonding",
            "• Etching: Apply a mild acid to create microscopic pores for bonding",
            "• Bonding Agent: Apply adhesive to create a strong bond between tooth and filling",
            "• Layering: Place composite material in thin layers, curing each with a special light",
            "• Shaping: Sculpt the filling to match your natural tooth anatomy",
            "• Polishing: Finish with high-gloss polish for a natural appearance",
            "",
            "Durability and Longevity:",
            "",
            "Modern composite fillings can last 7-10 years or longer with proper care. Factors affecting longevity include:",
            "",
            "• Oral Hygiene: Good brushing and flossing habits",
            "• Diet: Limiting sugary and acidic foods",
            "• Bruxism: Night guards can protect fillings from grinding damage",
            "• Regular Checkups: Early detection of any issues",
            "",
            "When Composite Fillings Are Ideal:",
            "",
            "• Visible Areas: Front teeth and visible back teeth",
            "• Small to Medium Cavities: Excellent for most cavity sizes",
            "• Chipped Teeth: Can repair minor chips and fractures",
            "• Gap Closure: Can close small spaces between teeth",
            "• Worn Teeth: Can restore worn tooth surfaces",
            "",
            "Care and Maintenance:",
            "",
            "• Daily Hygiene: Brush twice daily with fluoride toothpaste and floss daily",
            "• Regular Checkups: Professional cleanings and examinations every 6 months",
            "• Avoid Hard Foods: Don't chew ice, hard candy, or other hard objects",
            "• Protect from Grinding: Use a night guard if you grind your teeth",
            "",
            "Composite fillings represent the gold standard in modern restorative dentistry, combining excellent aesthetics with proven durability and safety. They allow us to restore your teeth while maintaining the natural beauty of your smile."
        ],
        heroImg: "/images/crown.svg",
        publishedAt: "2025-11-24",
    },
    // 9
    {
        slug: "teeth-whitening-facts-and-fallacies",
        title: "Teeth Whitening: Facts and Fallacies",
        excerpt: "Separate fact from fiction about teeth whitening and discover the safest, most effective methods for a brighter smile.",
        content: [
            "Teeth whitening is one of the most popular cosmetic dental treatments, but misinformation abounds. Understanding the facts can help you make informed decisions about whitening your smile safely and effectively.",
            "",
            "The Science of Tooth Color:",
            "",
            "Tooth color is determined by both the enamel (outer layer) and dentin (inner layer). Over time, both can become discolored due to:",
            "",
            "• Extrinsic Stains: Surface stains from coffee, tea, wine, tobacco, and certain foods",
            "• Intrinsic Stains: Internal discoloration from aging, medications, trauma, or excessive fluoride",
            "• Thinning Enamel: As enamel wears, more yellow dentin shows through",
            "",
            "Professional Whitening Options:",
            "",
            "• In-Office Whitening:",
            "  - Uses high-concentration peroxide gels (15-40%)",
            "  - Results visible in 1-2 hours",
            "  - Can lighten teeth 3-8 shades",
            "  - Professional supervision ensures safety",
            "",
            "• Take-Home Trays:",
            "  - Custom-fitted trays with lower-concentration gel (10-22%)",
            "  - Worn 30 minutes to 2 hours daily for 1-2 weeks",
            "  - Gradual, controlled whitening",
            "  - More cost-effective for maintenance",
            "",
            "Common Myths Debunked:",
            "",
            "• Myth: \"Whitening damages teeth\"",
            "  Fact: Professional whitening is safe when done correctly. Temporary sensitivity is normal and resolves quickly.",
            "",
            "• Myth: \"All whitening is the same\"",
            "  Fact: Professional treatments are more effective and safer than over-the-counter products.",
            "",
            "• Myth: \"Whitening works on all teeth\"",
            "  Fact: Crowns, fillings, and veneers don't whiten. Natural teeth may whiten at different rates.",
            "",
            "• Myth: \"More is better\"",
            "  Fact: Over-whitening can cause sensitivity and unnatural appearance. Follow professional recommendations.",
            "",
            "Over-the-Counter Products:",
            "",
            "• Whitening Toothpastes: Remove surface stains but don't change tooth color significantly",
            "• Whitening Strips: Can be effective but may cause uneven results and gum irritation",
            "• Whitening Pens: Convenient but limited effectiveness",
            "• Charcoal Products: No proven whitening benefit and may be abrasive",
            "",
            "Who Should Avoid Whitening:",
            "",
            "• Pregnant or Nursing Women: Safety not established",
            "• Children Under 16: Tooth development still occurring",
            "• Severe Sensitivity: May worsen existing sensitivity",
            "• Gum Disease: Should be treated before whitening",
            "• Cracked Teeth: Whitening agents may cause pain",
            "",
            "Maintaining Your Results:",
            "",
            "• Avoid Staining Foods: Limit coffee, tea, wine, and dark berries",
            "• Use a Straw: For beverages that stain",
            "• Rinse After Eating: Swish water after consuming staining foods",
            "• Regular Cleanings: Professional cleanings remove surface stains",
            "• Touch-Up Treatments: Periodic whitening maintains results",
            "",
            "What to Expect:",
            "",
            "• Temporary Sensitivity: Normal and usually resolves within 24-48 hours",
            "• Gum Irritation: Usually mild and temporary",
            "• Uneven Results: Some teeth may whiten faster than others",
            "• Results Duration: 6 months to 2 years, depending on habits",
            "",
            "Professional whitening is the safest and most effective way to brighten your smile. We can help you choose the best option based on your goals, budget, and lifestyle."
        ],
        heroImg: "/images/tooth-sparkle.svg",
        publishedAt: "2025-12-08",
    },
    // 10
    {
        slug: "how-to-handle-dental-emergencies",
        title: "How to Handle Dental Emergencies",
        excerpt: "Essential first-aid steps for common dental emergencies and when to seek immediate professional care.",
        content: [
            "Dental emergencies can happen at any time and often require immediate attention to prevent permanent damage or severe pain. Knowing how to respond can make the difference between saving and losing a tooth.",
            "",
            "Knocked-Out Tooth (Avulsed Tooth):",
            "",
            "• Time is Critical: The tooth has the best chance of survival if reimplanted within 30 minutes",
            "• Handle Carefully: Pick up the tooth by the crown (chewing surface), never the root",
            "• Clean Gently: Rinse with water if dirty, but don't scrub or remove tissue fragments",
            "• Reimplant if Possible: Try to place the tooth back in its socket, holding it in place with gentle pressure",
            "• Keep Moist: If you can't reimplant, store in milk, saliva, or a tooth preservation kit",
            "• Seek Immediate Care: Call us immediately—this is a true dental emergency",
            "",
            "Severe Toothache:",
            "",
            "• Rinse with Warm Water: Clean the area and remove any food debris",
            "• Floss Gently: Remove any trapped food between teeth",
            "• Cold Compress: Apply to the outside of your face to reduce swelling",
            "• Pain Relief: Take over-the-counter pain medication as directed",
            "• Avoid Heat: Don't apply heat to the area as it can worsen inflammation",
            "• Schedule Appointment: Even if pain subsides, see us to address the underlying cause",
            "",
            "Chipped or Broken Tooth:",
            "",
            "• Save Pieces: Collect any broken tooth fragments",
            "• Rinse Mouth: Use warm water to clean the area",
            "• Stop Bleeding: Apply gauze with gentle pressure if bleeding",
            "• Cold Compress: Reduce swelling with ice pack",
            "• Pain Management: Take pain medication if needed",
            "• Protect Sharp Edges: Cover with dental wax or sugarless gum to prevent cuts",
            "• See Us Soon: Schedule an appointment within 24 hours",
            "",
            "Lost Filling or Crown:",
            "",
            "• Save the Restoration: Keep the filling or crown if possible",
            "• Clean the Tooth: Gently clean the affected tooth",
            "• Temporary Protection: Use dental cement, dental wax, or sugarless gum to cover the tooth",
            "• Avoid Chewing: Don't chew on the affected side",
            "• Schedule Repair: See us within a few days to replace the restoration",
            "",
            "Abscess or Swelling:",
            "",
            "• Rinse with Salt Water: Mix 1/2 teaspoon salt in 8 ounces of warm water",
            "• Cold Compress: Apply to reduce swelling",
            "• Pain Relief: Take over-the-counter pain medication",
            "• Seek Immediate Care: Facial swelling can be serious—call us immediately",
            "• Don't Delay: This may indicate a serious infection requiring antibiotics",
            "",
            "Objects Caught Between Teeth:",
            "",
            "• Try Dental Floss: Gently work floss between teeth",
            "• Don't Use Sharp Objects: Avoid pins, needles, or other sharp tools",
            "• Rinse with Water: Sometimes vigorous rinsing can dislodge objects",
            "• See Us if Stuck: If you can't remove it, we can help safely",
            "",
            "Prevention Tips:",
            "",
            "• Wear Mouthguards: During sports and physical activities",
            "• Avoid Hard Foods: Don't chew ice, hard candy, or popcorn kernels",
            "• Don't Use Teeth as Tools: Never open packages or bottles with your teeth",
            "• Regular Checkups: Early detection prevents many emergencies",
            "",
            "When to Seek Immediate Care:",
            "",
            "• Severe Pain: Uncontrolled pain that doesn't respond to medication",
            "• Facial Swelling: Any swelling in the face or neck area",
            "• Knocked-Out Tooth: Time-sensitive situation requiring immediate attention",
            "• Signs of Infection: Fever, swelling, or pus drainage",
            "• Trauma: Any significant injury to the mouth or face",
            "",
            "Our Emergency Services:",
            "",
            "We provide emergency dental care and can often see patients the same day for urgent situations. Don't hesitate to call us—we're here to help when you need us most.",
            "",
            "Remember: When in doubt, it's always better to seek professional care sooner rather than later. Many dental problems worsen without treatment, and early intervention often leads to better outcomes."
        ],
        heroImg: "/images/tooth-pain.svg",
        publishedAt: "2025-12-22",
    },
    // 11
    {
        slug: "oral-health-for-children-building-good-habits",
        title: "Oral Health for Children: Building Good Habits",
        excerpt: "Tips for parents to encourage strong, healthy smiles.",
        content: [
            "Teach children to brush twice a day, floss daily, and limit sugary snacks from an early age.",
            "Routine dental visits make preventive care positive and stress-free for kids."
        ],
        heroImg: "",
        publishedAt: "2026-01-05",
    },
    // 12
    {
        slug: "dental-implants-benefits-and-process",
        title: "Dental Implants: Benefits and Process",
        excerpt: "Long-lasting tooth replacement that looks and feels natural.",
        content: [
            "Dental implants restore function and aesthetics after tooth loss.",
            "We’ll guide you through evaluation, placement, and restoring your confident smile."
        ],
        heroImg: "",
        publishedAt: "2026-01-19",
    },
    // 13
    {
        slug: "foods-for-healthy-teeth-and-gums",
        title: "Foods for Healthy Teeth and Gums",
        excerpt: "Smart nutrition for a stronger, brighter smile.",
        content: [
            "Crunchy vegetables, dairy, and plenty of water support oral health.",
            "Limit sticky sweets and drinks that fuel plaque and weaken enamel."
        ],
        heroImg: "",
        publishedAt: "2026-02-02",
    },
    // 14
    {
        slug: "the-role-of-dental-technology-in-modern-care",
        title: "The Role of Dental Technology in Modern Care",
        excerpt: "How advanced tools improve accuracy and comfort.",
        content: [
            "From digital x-rays to intraoral cameras, we use technology to enhance diagnostics and patient experience.",
            "Ask us how these innovations make your visits safer, faster, and more comfortable."
        ],
        heroImg: "",
        publishedAt: "2026-02-16",
    },
    // 15
    {
        slug: "how-to-overcome-dental-anxiety",
        title: "How to Overcome Dental Anxiety",
        excerpt: "Comfort-focused tips for a calm, positive dental experience.",
        content: [
            "If dental visits make you nervous, you’re not alone. We offer gentle techniques, clear explanations, and create a judgment-free environment.",
            "Let us know your concerns so we can make your next visit as comfortable as possible."
        ],
        heroImg: "",
        publishedAt: "2026-03-02",
    },
];

export function parseDate(dateString) {
    return new Date(dateString + "T00:00:00Z");
}

export function isPublished(post, now = new Date()) {
    return parseDate(post.publishedAt) <= now;
}

export function getPublishedPosts(now = new Date()) {
    return posts.filter((p) => isPublished(p, now)).sort((a, b) => parseDate(b.publishedAt) - parseDate(a.publishedAt));
}

export function getPostBySlug(slug) {
    return posts.find((p) => p.slug === slug) || null;
}

export function getAllSlugs() {
    return posts.map((p) => p.slug);
}


